name: wildfire_map_app
description: A new Flutter project for wildfire tracking

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0    
  latlong2: ^0.9.0   
  http: ^1.2.0            
  csv: ^5.0.2             
  flutter_map_marker_cluster: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Performance optimizations
  assets:
    - assets/images/
  
  # Fonts (if needed later)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
